name: Build Documents

on:
  workflow_dispatch:
  push:
    branches:
      - master
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  filters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          docker:
            - 'docker/**/*'
          v5:
            - '5.0/**/*'
          v4:
            - '4.0/**/*'
    outputs:
      docker: ${{ steps.filter.outputs.docker }}
      v4: ${{ steps.filter.outputs.v4 }}
      v5: ${{ steps.filter.outputs.v5 }}

  build-image:
    if: needs.filters.outputs.docker == 'true'
    needs: filters
    uses: owasp/asvs/.github/workflows/build-and-publish-docker-image.yml@master

  build-v4:
    if: ${{ always() && needs.filters.outputs.v4 == 'true' }}
    needs: 
      - build-image
      - filters
    uses: owasp/asvs/.github/workflows/create-4.0-outputs.yml@master
    
  build-v5:
    if: ${{ always() && needs.filters.outputs.v5 == 'true' }}
    needs: 
      - build-image
      - filters
    uses: owasp/asvs/.github/workflows/create-5.0-outputs.yml@master
