# Name of this GitHub Actions workflow.
name: Generate Outputs

on:
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  prepare_container:
    runs-on: ubuntu-latest
    name: Generate container
    steps:
      - uses: actions/checkout@v3
      - run: make all
      - uses: actions/upload-artifact@v3
        with:
          name: ASVS 5.0 Bleeding Edge
          path: 5.0/dist/en/
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}