# Name of this GitHub Actions workflow.
name: Generate Outputs

on:
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}

jobs:
  prepare_container:
    runs-on: ubuntu-latest
    name: Generate container
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Make image
        run: make docker
      - name: Save docker image
        run: docker save asvs/documentbuilder > asvs_documentbuilder.tar
      - name: Upload container image
        uses: actions/upload-artifact@v2
        with:
          name: asvs_documentbuilder
          path: asvs_documentbuilder.tar
  create_output:
    runs-on: ubuntu-latest
    needs: prepare_container
    name: Create outputs
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download container
        uses: actions/download-artifact@v2
      - name: Load docker image
        run: |
          docker load --input asvs_documentbuilder/asvs_documentbuilder.tar 
      - name: Make outputs
        run: make all

